services:
  # ========== API ==========
  - type: web
    name: minecraft-payment-api
    runtime: node
    plan: free
    buildCommand: cd api && npm install
    startCommand: cd api && node index.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: MERCADO_PAGO_ACCESS_TOKEN
        sync: false
      - key: API_URL
        sync: false
      - key: MINECRAFT_HOST
        sync: false
      - key: RCON_PORT
        value: 25575
      - key: RCON_PASSWORD
        sync: false

  # ========== BOT DISCORD (Background Worker) ==========
  - type: worker
    name: minecraft-discord-bot
    runtime: node
    plan: free
    buildCommand: cd bot-discord && npm install
    startCommand: cd bot-discord && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false
      - key: API_URL
        sync: false
